### ISSUE TITLE
Training with own dataset

### ISSUE THREAD

**Issue by JJLimmm** [jsmithdlc/CenterNet-Thermal-Human-Pose-Estimation#1]
Hi @jsmithdlc , thanks for the work you've done here. Can i check if you remember the steps on training and finetuning your dla model with my own dataset?

**Comment by jsmithdlc** [comment]
Hi @JJLimmm. If you want to use your own dataset I'd recommend following the steps detailed [here](https://github.com/xingyizhou/CenterNet/blob/master/readme/DEVELOP.md). After setup, you can then train and finetune your model using the instructions in the [readme](https://github.com/jsmithdlc/CenterNet-ThermalPose#training-models). The original CenterNet repo also contains some [useful indications](https://github.com/xingyizhou/CenterNet/blob/master/readme/GETTING_STARTED.md) on training procedures. 

Hope this helps!

**Comment by JJLimmm** [comment]
Hi @jsmithdlc , Thanks for the prompt reply! Will try that out now

**Comment by JJLimmm** [comment]
Hi again, @jsmithdlc, i am now trying to use your pretrained model to help produce the output keypoints and annotations for my thermal image dataset. Is there a script that you used for converting the .csv output to KITTI/COCO format?

**Comment by jsmithdlc** [comment]
Sorry I don't have that script. This guide: https://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch might be useful for that
